# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@stable'
    'frameworks/kdoctools': '@stable'
    'frameworks/kio': '@stable'
    'frameworks/ki18n': '@stable'
    'frameworks/kconfig': '@stable'
    'frameworks/kconfigwidgets': '@stable'
    'frameworks/kdbusaddons': '@stable'
    'frameworks/kidletime': '@stable'
    'frameworks/kjobwidgets': '@stable'
    'frameworks/knotifications': '@stable'
    'frameworks/kwindowsystem': '@stable'
    'frameworks/kxmlgui': '@stable'
    'frameworks/ktextwidgets': '@stable'
    'frameworks/kcalendarcore': '@stable'
