# SPDX-FileCopyrightText: 2024 Thiago Masato Costa Sueto <thiago.sueto@kde.org>
#
# SPDX-License-Identifier: CC0-1.0

version = 1
SPDX-PackageName = "ktimetracker"
SPDX-PackageSupplier = "Thiago Masato Costa Sueto <thiago.sueto@kde.org>"
SPDX-PackageDownloadLocation = "https://invent.kde.org/pim/ktimetracker"

[[annotations]]
path = ".flatpak-manifest.json"
precedence = "aggregate"
SPDX-FileCopyrightText = "2023 Thiago Masato Costa Sueto <thiago.sueto@kde.org>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["icons/**.png", "icons/**.svg"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2014 Uri Herrera <uri_herrera@nitrux.in> and others"
SPDX-License-Identifier = "LGPL-3.0-only"

[[annotations]]
path = ["test/**.ics", "test/README", "src/tests/**.ics", "src/tests/**.planner", "src/pics/**.xpm", "src/pics/**.gif", "doc/**.png"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2019 Alexander Potashev <aspotashev@gmail.com>"
SPDX-License-Identifier = "CC0-1.0"
